import { Plan } from '../types';

export const plans: Plan[] = [
  {
    id: 'basic',
    name: 'Plano Básico',
    price: 97,
    image: '/images/bot-basic.jpg',
    badge: 'STARTER',
    badgeColor: 'from-amber-600 to-amber-800',
    groups: 3,
    messages: '1.000 mensagens/dia',
    support: 'Suporte por e-mail',
    description:
      'Perfeito para quem está começando. O bot será configurado no seu grupo de WhatsApp para responder automaticamente, enviar boas-vindas para novos membros, moderar conteúdo e gerenciar links. Ideal para pequenos negócios e comunidades.',
    features: [
      'Bot ativo em até 3 grupos',
      'Até 1.000 mensagens automáticas por dia',
      'Mensagens de boas-vindas personalizadas',
      'Moderação automática de spam e links',
      'Respostas automáticas com palavras-chave',
      'Painel básico de estatísticas',
      'Suporte por e-mail (resposta em 48h)',
      'Atualizações mensais do bot',
    ],
  },
  {
    id: 'pro',
    name: 'Plano Profissional',
    price: 197,
    image: '/images/bot-pro.jpg',
    badge: 'PRO',
    badgeColor: 'from-slate-400 to-slate-600',
    groups: 10,
    messages: '5.000 mensagens/dia',
    support: 'Suporte prioritário via WhatsApp',
    description:
      'Para quem precisa de mais poder. O bot profissional inclui inteligência artificial para respostas inteligentes, agendamento de mensagens, enquetes automáticas e integração com sistemas de pagamento. Perfeito para negócios em crescimento.',
    features: [
      'Bot ativo em até 10 grupos',
      'Até 5.000 mensagens automáticas por dia',
      'Respostas com Inteligência Artificial (IA)',
      'Agendamento de mensagens e campanhas',
      'Enquetes e votações automáticas',
      'Integração com sistemas de pagamento',
      'Relatórios avançados com gráficos',
      'Suporte prioritário via WhatsApp (24h)',
      'Personalização completa de mensagens',
      'Backup automático de conversas',
    ],
  },
  {
    id: 'enterprise',
    name: 'Plano Enterprise',
    price: 497,
    image: '/images/bot-enterprise.jpg',
    badge: 'ENTERPRISE',
    badgeColor: 'from-yellow-400 to-yellow-600',
    groups: 50,
    messages: 'Mensagens ilimitadas',
    support: 'Gerente de conta dedicado',
    description:
      'A solução definitiva. Bot com IA avançada, múltiplas instâncias, API personalizada, webhooks, CRM integrado e suporte 24/7 com gerente dedicado. Para empresas que precisam de automação total em grande escala.',
    features: [
      'Bot ativo em até 50 grupos (ou ilimitado)',
      'Mensagens ilimitadas por dia',
      'IA avançada com aprendizado contínuo',
      'API personalizada para integração',
      'Webhooks para sistemas externos',
      'CRM integrado para gestão de leads',
      'Multi-atendentes simultâneos',
      'Chatbot com fluxos personalizados',
      'Relatórios em tempo real + exportação',
      'Suporte 24/7 com gerente dedicado',
      'Treinamento da equipe incluso',
      'SLA de 99.9% de uptime garantido',
    ],
  },
];
